# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://shadowrefer.com
title: Shadow Refer
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2019 My Name. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
